# -*- coding: utf-8 -*-
"""Tweet_Download.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13c95G8NcpP1MQ4atrYKurZOmOwuU_FUQ
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install tweepy

import tweepy
import csv
####input your credentials here

consumer_key = ''
consumer_secret = ''
access_token = ''
access_token_secret = ''

#consumer_key = '2c3qLmjM7LqzKHqPk3EOxl4fs'
#consumer_secret = 'RFg8y2GRqnKsyS8I8Fx3p1qS4TNaALpzt6CFpmIdTRYPrmkE98'
#access_token = '1250083816800124928-JNUE09xOZwE2ADzqHw01NsJmrrZ2Lo'
#access_token_secret = 'uvCsAEHmEvppC0ZO2gy7KyQVFpHKzTW5K2ALsLUaStOCB'

import time



auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth,wait_on_rate_limit=True,wait_on_rate_limit_notify=True)


already_downloaded=open('drive/My Drive/tweet_downloaded/741.tsv', 'r')

already_list=dict()

j=0

for line in already_downloaded:
    j=j+1
    line=line.split('\n')[0].split('\t')[0]
    already_list[line]=1



tsvFile = open('drive/My Drive/tweet_downloaded/741.tsv', 'a')

file=open('drive/My Drive/tweet_ids/corona_tweets_741.csv','r')

already_downloaded.close()


all_ids=list()
cur_list=list()
i=0

for line in file:

    if i==90:
        all_ids.append(cur_list)
        i=0
        cur_list=list()
    else:
        if line.split('\n')[0].split(',')[0] not in already_list:
            cur_list.append(line.split('\n')[0].split(',')[0])
            i=i+1


i=0

for cur_list in all_ids[0:8100]:
    if j>30000:
        break

    i=i+1
    if i%10==0:
        time.sleep(3)


    if True:
        tweets = api.statuses_lookup(id_=cur_list,tweet_mode="extended")
        for tweet in tweets:

            location = tweet.author.location
            if location == '':
                location = 'UnknownLocation'

            tsvFile.writelines('\t'.join([tweet.id_str, location, tweet.full_text.replace('\n',' ')]) + '\n');
            j=j+1
            print(location+'\t'+tweet.full_text)


    else:
        print("Not av")

tsvFile.close()